defaults:
  - optimizer:  radam
  - optimizer_assister: null

logger:
  project:  test
  save_dir: ./log/
  offline:  False # False if you want to sync log to wandb server.
  name: test
  version:  null

checkpoint_path:  ./ckpt/
num_workers:  4
sleep:  0 # This is for delayed execution.
seed: 7777777
model:  v1

set_float32_matmul_precision:  high # medium or high
compile_model:  False
